version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn bike_rental.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ..:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bike_rental
      POSTGRES_USER: bike_rental_user
      POSTGRES_PASSWORD: bike_rental_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "celery -A bike_rental worker -l info & celery -A bike_rental beat -l info"
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume: